#!/bin/bash

title="System Information Report for $HOSTNAME"
ts="$(date)"

echo "<html>
	<head>
		<title>$title</title>
	</head?
	<body>
		<h1>$title</h1>

		<p>$ts</p>

		<h2>Storage Utilization</h2>
		<pre>$(df -h)</pre>

		<h2>By user</h2>
		<pre>$(du)</pre>
	</body>
</html>"
